version: '3.9'

services:

  backend:
    build:
      target: production
    restart: always
    env_file:
      - .env.prod

  frontend:
    build:
      target: production
    restart: always

  postgres:
    restart: always
    env_file:
      - .env.prod